/***********TRIGGER AUDITORIA CREADO/MODIFICADO POR*****************/

-- Trigger de auditoría para FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PAIS_TB
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_CANTON_TB
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_DISTRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_USUARIO_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PRODUCTO_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PROMOCION_TB
CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PRODUCTO_PROMOCION_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROMOCION_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_INVENTARIO_TB
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PROVEEDOR_TB
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PRODUCTO_PROVEEDOR_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROVEEDOR_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_CARRITO_TB
CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_DETALLE_CARRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_CARRITO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_METODO_PAGO_TB
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_LOCAL_TB
CREATE OR REPLACE TRIGGER FIDE_LOCAL_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LOCAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_PEDIDO_TB
CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditoría para FIDE_DETALLE_PEDIDO_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_PEDIDO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/