/************TRIGGERS AUDITORIA FECHA CREACION/MODIFICACION********************/
/***************TRIGGERS AUDITORIA ACCION*************/
-- Trigger para FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_ESTADO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PAIS_TB
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PAIS_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PROVINCIA_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_CANTON_TB
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_CANTON_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_ACCION_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_DISTRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_DISTRITO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_DIRECCION_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_ACCION_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_USUARIO_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_USUARIO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PROMOCION_TB
CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PROMOCION_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PROMOCION_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_PROMOCION_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROMOCION_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PRODUCTO_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_PROMOCION_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROMOCION_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PRODUCTO_PROMOCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_INVENTARIO_TB
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_INVENTARIO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PROVEEDOR_TB
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PROVEEDOR_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PROVEEDOR_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_PROVEEDOR_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROVEEDOR_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PRODUCTO_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PRODUCTO_PROVEEDOR_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_PROVEEDOR_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PRODUCTO_PROVEEDOR_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_CARRITO_TB
CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_CARRITO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_DETALLE_CARRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_CARRITO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_DETALLE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_DETALLE_CARRITO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_DETALLE_CARRITO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_DETALLE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/


-- Trigger para FIDE_METODO_PAGO_TB
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_METODO_PAGO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_LOCAL_TB
CREATE OR REPLACE TRIGGER FIDE_LOCAL_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_LOCAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_LOCAL_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_LOCAL_TB_ACCION_TRG
BEFORE INSERT ON FIDE_LOCAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_PEDIDO_TB
CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_PEDIDO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_PEDIDO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- Trigger para FIDE_DETALLE_PEDIDO_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_PEDIDO_TB_CREADO_MOD_CREACION
BEFORE INSERT ON FIDE_DETALLE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger para FIDE_DETALLE_PEDIDO_TB ACCION
CREATE OR REPLACE TRIGGER FIDE_DETALLE_PEDIDO_TB_ACCION_TRG
BEFORE INSERT ON FIDE_DETALLE_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/