CREATE TABLE ESTADO (
    ID_ESTADO NUMBER(1) PRIMARY KEY,
      VARCHAR2(50) NOT NULL
);

-- Tabla de Usuarios
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR2(20),
    ID_ESTADO NUMBER(1) NOT NULL,
    ID_DIRECCION NUMBER, 
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

-- Tabla de Dirección
CREATE TABLE DIRECCION (
    ID_DIRECCION NUMBER PRIMARY KEY,
    CALLE VARCHAR2(100),
    NUMERO_CASA VARCHAR2(10),
    OTRAS_SENAS VARCHAR2(100),
    ID_PAIS NUMBER,
    ID_PROVINCIA NUMBER,
    ID_CANTON NUMBER,
    ID_DISTRITO NUMBER,
    ID_ESTADO NUMBER(1),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA),    
    FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON),
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- Tabla de País
CREATE TABLE PAIS (
    ID_PAIS NUMBER PRIMARY KEY,
    PAIS VARCHAR2(50) NOT NULL
);

-- Tabla de Provincia
CREATE TABLE PROVINCIA (
    ID_PROVINCIA NUMBER PRIMARY KEY,
    PROVINCIA VARCHAR2(50) NOT NULL
);

-- Tabla de Cantón
CREATE TABLE CANTON (
    ID_CANTON NUMBER PRIMARY KEY,
    CANTON VARCHAR2(50) NOT NULL
);

-- Tabla de Distrito
CREATE TABLE DISTRITO (
    ID_DISTRITO NUMBER PRIMARY KEY,
    DISTRITO VARCHAR2(50) NOT NULL
);


-- Tabla de Producto
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER(10, 2) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO),
);

-- Tabla de Promoción
CREATE TABLE PROMOCION (
    ID_PROMOCION NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCUENTO_PORCENTAJE NUMBER(5, 2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);


-- Tabla de Promoción de Producto
CREATE TABLE PRODUCTO_PROMOCION (
    ID_PROMOCION NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    PRIMARY KEY (ID_PROMOCION, ID_PRODUCTO),
    FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCION (ID_PROMOCION),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Inventario
CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    FECHA_ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Proveedor
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(15),
    EMAIL VARCHAR2(100) NOT NULL,
    ID_DIRECCION NUMBER, 
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

-- Tabla de Producto Proveedor
CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Carrito (Temporal para guardar productos antes de hacer un pedido)
CREATE TABLE CARRITO (
    ID_CARRITO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Detalle Carrito (Productos dentro del Carrito)
CREATE TABLE DETALLE_CARRITO (
    ID_DETALLE_CARRITO NUMBER PRIMARY KEY,
    ID_CARRITO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    SUBTOTAL NUMBER(10, 2),
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO (ID_CARRITO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);


-- Tabla de Pedido (Generado al confirmar el Carrito)
CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    ID_METODO_PAGO NUMBER NOT NULL,
    FECHA_PEDIDO DATE DEFAULT SYSDATE,
    TOTAL NUMBER(10, 2) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    ID_LOCAL NUMBER NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO (ID_METODO_PAGO),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL (ID_LOCAL),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Detalle Pedido (Productos dentro del Pedido)
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    SUBTOTAL NUMBER(10, 2),
    TOTAL NUMBER(10, 2)
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);


-- Tabla de Método Pago
CREATE TABLE METODO_PAGO (
    ID_METODO_PAGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

-- Tabla de Local
CREATE TABLE LOCAL (
    ID_LOCAL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_DIRECCION NUMBER,
    TELEFONO VARCHAR2(15),
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO),
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);