-- Secuencia para id de la tabla FIDE_DIRECCION_TB
CREATE SEQUENCE FIDE_DIRECCION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;                                                                                                                                                                                    

--- INSERTAR DIRECCION ---
CREATE OR REPLACE FUNCTION FIDE_DIRECCION_TB_INSERTAR_DIRECCION_FN (
    P_CALLE IN VARCHAR2,
    P_NUMERO_CASA IN VARCHAR2,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ID_PAIS IN NUMBER,
    P_ID_PROVINCIA IN NUMBER,
    P_ID_CANTON IN NUMBER,
    P_ID_DISTRITO IN NUMBER
) 
RETURN NUMBER
IS
    V_ID_DIRECCION NUMBER;
BEGIN
    -- Insertar la nueva direccion
    INSERT INTO FIDE_DIRECCION_TB (ID_DIRECCION, CALLE, NUMERO_CASA, OTRAS_SENAS, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO)
    VALUES (FIDE_DIRECCION_ID_SEQ.NEXTVAL, P_CALLE, P_NUMERO_CASA, P_OTRAS_SENAS, P_ID_PAIS, P_ID_PROVINCIA, P_ID_CANTON, P_ID_DISTRITO)
    RETURNING ID_DIRECCION INTO V_ID_DIRECCION;

    -- Retornar el ID de la nueva direccion creada
    RETURN V_ID_CURSO;
END;
