-- Secuencia para id de la tabla FIDE_DIRECCION_TB
CREATE SEQUENCE FIDE_DIRECCION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;                                                                                                                                                                                    
-- Secuencia para la tabla FIDE_PAIS_TB
CREATE SEQUENCE FIDE_PAIS_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_ESTADO_TB
CREATE SEQUENCE FIDE_ESTADO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PROVINCIA_TB
CREATE SEQUENCE FIDE_PROVINCIA_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_CANTON_TB
CREATE SEQUENCE FIDE_CANTON_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_DISTRITO_TB
CREATE SEQUENCE FIDE_DISTRITO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_USUARIO_TB
CREATE SEQUENCE FIDE_USUARIO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PRODUCTO_TB
CREATE SEQUENCE FIDE_PRODUCTO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PROMOCION_TB
CREATE SEQUENCE FIDE_PROMOCION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PRODUCTO_PROMOCION_TB
CREATE SEQUENCE FIDE_PRODUCTO_PROMOCION_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_INVENTARIO_TB
CREATE SEQUENCE FIDE_INVENTARIO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PROVEEDOR_TB
CREATE SEQUENCE FIDE_PROVEEDOR_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PRODUCTO_PROVEEDOR_TB
CREATE SEQUENCE FIDE_PRODUCTO_PROVEEDOR_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_CARRITO_TB
CREATE SEQUENCE FIDE_CARRITO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_DETALLE_CARRITO_TB
CREATE SEQUENCE FIDE_DETALLE_CARRITO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_METODO_PAGO_TB
CREATE SEQUENCE FIDE_METODO_PAGO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_LOCAL_TB
CREATE SEQUENCE FIDE_LOCAL_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_PEDIDO_TB
CREATE SEQUENCE FIDE_PEDIDO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Secuencia para la tabla FIDE_DETALLE_PEDIDO_TB
CREATE SEQUENCE FIDE_DETALLE_PEDIDO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

--- INSERTAR DIRECCION ---
CREATE OR REPLACE FUNCTION FIDE_DIRECCION_TB_INSERTAR_DIRECCION_FN (
    P_CALLE IN VARCHAR2,
    P_NUMERO_CASA IN VARCHAR2,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ID_PAIS IN NUMBER,
    P_ID_PROVINCIA IN NUMBER,
    P_ID_CANTON IN NUMBER,
    P_ID_DISTRITO IN NUMBER
) 
RETURN NUMBER
IS
    V_ID_DIRECCION NUMBER;
BEGIN
    -- Insertar la nueva direccion
    INSERT INTO FIDE_DIRECCION_TB (ID_DIRECCION, CALLE, NUMERO_CASA, OTRAS_SENAS, ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO)
    VALUES (FIDE_DIRECCION_ID_SEQ.NEXTVAL, P_CALLE, P_NUMERO_CASA, P_OTRAS_SENAS, P_ID_PAIS, P_ID_PROVINCIA, P_ID_CANTON, P_ID_DISTRITO)
    RETURNING ID_DIRECCION INTO V_ID_DIRECCION;

    -- Retornar el ID de la nueva direccion creada
    RETURN V_ID_DIRECCION;
END;
/