-- SELECT TABLESPACE_NAME, FILE_NAME, BYTES /1024/1021 AS SIZE_MB FROM dba_data_files;
-- SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;

-- Crear tablespaces para el usuario FIDE_PROYECTO_FINAL_USUARIO_ADMIN
CREATE TABLESPACE FIDE_PROYECTOFINAL_TBS DATAFILE 'C:\APP\GCASTRO\ORADATA\ORCL\FIDE_PROYECTOFINAL_TBS.DBF' SIZE 100M;
CREATE TABLESPACE FIDE_PROYECTOFINALTEMP_TBS DATAFILE 'C:\APP\GCASTRO\ORADATA\ORCL\FIDE_PROYECTOFINALTEMP_TBS.DBF' SIZE 50M;
-----------------------------------------------------------------------------------------------

-- Crear perfil para el usuario FIDE_PROYECTO_FINAL_USUARIO_ADMIN
CREATE PROFILE FIDE_PROYECTO_FINAL_PROF
LIMIT
    SESSIONS_PER_USER 1 
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_LIFE_TIME 90;
-----------------------------------------------------------------------------------------------

-- Crear usuario ProyectoFinal
CREATE USER FIDE_PROYECTO_FINAL_USUARIO_ADMIN 
IDENTIFIED BY 123
DEFAULT TABLESPACE FIDE_PROYECTOFINAL_TBS
TEMPORARY TABLESPACE FIDE_PROYECTOFINALTEMP_TBS
PROFILE FIDE_PROYECTO_FINAL_PROF;
-----------------------------------------------------------------------------------------------

-- Asignar permisos al usuario FIDE_PROYECTO_FINAL_USUARIO_ADMIN
GRANT CONNECT, RESOURCE, CREATE TABLE TO FIDE_PROYECTO_FINAL_USUARIO_ADMIN;

-----------------------------------------------------------------------------------------------
-- Crear roles Admin - Cliente
CREATE ROLE ADMIN_ROLE;
CREATE ROLE CLIENTE_ROLE;

-- Otorgar permisos a ADMIN_ROLE
-- Privilegios de creación
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO ADMIN_ROLE;
-- Privilegios sobre todas las tablas
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO ADMIN_ROLE;
-- Privilegios avanzados
GRANT ALTER ANY TABLE, DROP ANY TABLE TO ADMIN_ROLE;

-- Otorgar permisos a CLIENTE_ROLE -- Ejemplo
GRANT SELECT ON FIDE_PROYECTO_FINAL_USUARIO.nombreTabla TO CLIENTE_ROLE;
GRANT INSERT, UPDATE ON FIDE_PROYECTO_FINAL_USUARIO.nombreTabla TO CLIENTE_ROLE;
GRANT EXECUTE ON FIDE_PROYECTO_FINAL_USUARIO.nombrePackage TO CLIENTE_ROLE;

-- Asignar role ADMIN al usuario FIDE_PROYECTO_FINAL_USUARIO_ADMIN
GRANT ADMIN_ROLE TO FIDE_PROYECTO_FINAL_USUARIO_ADMIN;

-----------------------------------------------------------------------------------------------

-- Activar auditoría en cada tabla
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_ESTADO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PAIS_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PROVINCIA_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_CANTON_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_DISTRITO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_DIRECCION_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_USUARIO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PRODUCTO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PROMOCION_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PRODUCTO_PROMOCION_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_INVENTARIO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PRODUCTO_PROVEEDOR_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_CARRITO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_DETALLE_CARRITO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_METODO_PAGO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_LOCAL_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_PEDIDO_TB BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON FIDE_PROYECTO_FINAL_USUARIO_ADMIN.FIDE_DETALLE_PEDIDO_TB BY ACCESS;