-- 1. Tabla Estado
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (0, 'Inactivo');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (1, 'Activo');
INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, DESCRIPCION) VALUES (2, 'Sin estado');
